apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: payment-service
  labels:
    app.kubernetes.io/part-of: payment-service
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  source:
    git:
      url: https://github.com/timosalm/tap-workshops-payment-service.git
      ref:
        branch: main
  serviceClaims:
  - name: db
    ref:
      apiVersion: services.apps.tanzu.vmware.com/v1alpha1
      kind: ClassClaim
      name: postgres-1
  build:
    env:
    - name: BP_JVM_VERSION
      value: "17"
