#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
#@ load("@ytt:json", "json")
---
apiVersion: learningcenter.tanzu.vmware.com/v1beta1
kind: Workshop
metadata:
  name: tap-operator-workshop
spec:
  title: TAP for Operators
  description: A workshop that demonstrates capabilities of VMware Tanzu Application Platform for operators.
  vendor: tanzu.vmware.com
  difficulty: beginner
  duration: 60m
  url: https://github.com/tsalm-pivotal/tap-operator-workshop
  content:
    image: #@ "{}/tap-workshop/tap-operator-workshop:latest".format(data.values.container_registry.hostname)
    files: #@ "github.com/{}/tap-operator-workshop?ref={}".format(data.values.workshop_git.username,data.values.workshop_git.branch)
  session:
    namespaces:
      budget: custom
    applications:
      terminal:
        enabled: true
        layout: split
      console:
        enabled: true
      editor:
        enabled: true
    env: 
    - name: TAP_INGRESS
      value: #@ data.values.tap.ingress_domain
    objects:
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: default-permit-deliverable
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: deliverable
      subjects:
        - kind: ServiceAccount
          name: default
          namespace: $(session_namespace)
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: default-permit-workload
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: workload
      subjects:
        - kind: ServiceAccount
          name: default
          namespace: $(session_namespace)
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: Role
      metadata:
        name: workload-gitops
        namespace: $(session_namespace)
      rules:
      - apiGroups:
        - carto.run
        resources:
        - workloads
        verbs:
        - '*'
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: default-workload-gitops
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: Role
        name: workload-gitops
      subjects:
        - kind: ServiceAccount
          name: default
          namespace: $(session_namespace)
    # Permissions for workshop session
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: $(session_namespace)-session-cr
      rules:
      - apiGroups:
        - kappctrl.k14s.io
        resources:
        - apps
        verbs:
        - 'get'
        - 'list'
      - apiGroups:
        - carto.run
        resources:
        - workloads
        verbs:
        - 'get'
        - 'list'
      - apiGroups:
        - tekton.dev
        resources:
        - pipelines
        verbs:
        - 'get'
        - 'list'
      - apiGroups:
        - scanning.apps.tanzu.vmware.com
        resources:
        - scanpolicies
        verbs:
        - 'get'
        - 'list'
        - 'create'
        - 'update'
        - 'patch'
    - apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: $(session_namespace)-session-rb
        namespace: $(session_namespace)
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: $(session_namespace)-session-cr
      subjects:
        - kind: ServiceAccount
          namespace: $(workshop_namespace)
          name: $(service_account)
    # Install grype
    - apiVersion: packaging.carvel.dev/v1alpha1
      kind: PackageInstall
      metadata:
        name: $(session_namespace)-grype
        namespace: tap-install
      spec:
        serviceAccountName: tap-install-sa
        packageRef:
          refName: grype.scanning.apps.tanzu.vmware.com
          versionSelection:
            constraints: ">=0.0.0"
            prereleases:
              identifiers: [beta, build]
        values:
        - secretRef:
            name: $(session_namespace)-grype-values
    - apiVersion: v1
      kind: Secret
      metadata:
        name: $(session_namespace)-grype-values
        namespace: tap-install
      stringData:
        values.yaml: |
          ---
          namespace: $(session_namespace)
          targetImagePullSecret: registry-credentials
    - apiVersion: v1
      data:
        ca.crt: #@ data.values.metadatastore.app_tls_cert.ca_crt_base64
        tls.crt: #@ data.values.metadatastore.app_tls_cert.tls_crt_base64
        tls.key: #@ data.values.metadatastore.app_tls_cert.tls_key_base64
      kind: Secret
      metadata:
        name: app-tls-cert
      type: kubernetes.io/tls
    # Resources
    - apiVersion: v1
      kind: Secret
      metadata:
        name: registry-credentials
      type: kubernetes.io/dockerconfigjson
      data:
        #@ docker_auth = base64.encode("{}:{}".format(data.values.container_registry.username, data.values.container_registry.password))
        #@ docker_creds = {"username": data.values.container_registry.username, "password": data.values.container_registry.password, "auth": docker_auth}
        .dockerconfigjson: #@ base64.encode(json.encode({"auths": {data.values.container_registry.hostname: docker_creds}}))
    - apiVersion: v1
      kind: Secret
      metadata:
        annotations:
          tekton.dev/git-0: #@ base64.encode(data.values.gitops.host)
        name: git-https
      data:
        username: #@ base64.encode(data.values.gitops.username)
        password: #@ base64.encode(data.values.gitops.password)
    - apiVersion: kappctrl.k14s.io/v1alpha1
      kind: App
      metadata:
        name: workload-gitops
      spec:
        serviceAccountName: default
        fetch:
        - git:
            url: https://github.com/tsalm-vmware/tap-operator-workshop.git
            ref: origin/main
            subPath: samples/workload-gitops
        template:
        - ytt: {}
        deploy:
        - kapp: {}
    - apiVersion: tekton.dev/v1beta1
      kind: Pipeline
      metadata:
        name: developer-defined-tekton-pipeline
        labels:
          apps.tanzu.vmware.com/pipeline: test     # (!) required
      spec:
        params:
          - name: source-url                       # (!) required
          - name: source-revision                  # (!) required
          - name: source-sub-path
            default: "."
        tasks:
          - name: test
            params:
              - name: source-url
                value: $(params.source-url)
              - name: source-revision
                value: $(params.source-revision)
              - name: source-sub-path
                value: $(params.source-sub-path)
            taskSpec:
              params:
                - name: source-url
                - name: source-revision
                - name: source-sub-path
              steps:
                - name: test
                  image: gradle
                  script: |-
                    cd `mktemp -d`

                    wget -qO- $(params.source-url) | tar xvz -m
                    cd $(params.source-sub-path)
                    ./mvnw test